#!/usr/bin/env ruby

class Opts
  attr_reader :arguments

  def initialize(commands)
    @options = {}
    @arguments = []

    parse(commands)
  end

  def option(name, type, default = nil)
    if @options.key?(name)
      case type
      when 'integer'
        @options[name].to_i
      when 'float'
        @options[name].to_f
      when 'boolean'
        @options[name] == 'true'
      when 'string'
        @options[name]
      else
        raise "Unknown option type [#{type}]"
      end
    elsif default.nil?
      raise "Missing option [#{name}]"
    else
      default
    end
  end

  private

  def parse(commands)
    end_of_options = false

    while commands.any?
      x = commands.shift

      if end_of_options
        @arguments << x
      elsif x == '--'
        end_of_options = true
      elsif x.start_with?('--')
        y = commands.shift
        @options[x] = y
      else
        @arguments << x
        end_of_options = true
      end
    end
  end
end

o = Opts.new(ARGV)
model = o.option('--model', 'string')
query = o.option('--query', 'string', 'why is the sky blue')

def run(model, query)
  t1 = Time.now
  x = `ollama run #{model} #{query} --verbose 2>&1`

  er = nil
  pr = nil

  x.split("\n").each do |line|
    if line =~ /^eval rate:\s+([.0-9]+) tokens/
      er = $1.to_f
    elsif line =~ /^prompt eval rate:\s+ ([.0-9]+) tokens/
      pr = $1.to_f
    end
  end

  [pr, er, Time.now - t1]
end

def average(list)
  t = 0.0

  list.each do |v|
    t += v
  end

  t / list.size
end

puts "Model : #{model}"
puts "Query : #{query}"

puts "Run dry"
run(model, 'hi')

prs = []
ers = []

(1..5).each do |i|
  pr, er, t = run(model, query)
  puts "Run #{i} Prompt rate #{pr}, evel rate #{er} in #{format("%.2f", t)} seconds"

  prs << pr
  ers << er
end

puts "Prompt rate : %8.3f %8.3f %8.3f" % [prs.min, average(prs), prs.max]
puts "Eval rate ..: %8.3f %8.3f %8.3f" % [ers.min, average(ers), ers.max]
