#!/usr/bin/env ruby

require 'colorize'

unless File.exist?('tags.csv')
  warn "We need a tags.csv from ollama-dump"
  exit 1
end

bash_output = ARGV.include?('-s')

from_tags = {}

File.open('tags.csv', 'r').each do |line|
  model, tag, hash, size = line.chomp.split(',')
  from_tags[tag] = {hash: hash, size: size}
end

c = 0

`ollama list`.split("\n").sort.each do |line|
  next if line.include?('NAME')

  model_tag, hash, _ = line.chomp.split(/\s+/, 4)
  model_tag = model_tag.split('/').last if model_tag.include?('/')

  if from_tags.key?(model_tag)
    if from_tags[model_tag][:hash] == hash
      # puts "#{model_tag.green} is up to date"
    else
      if bash_output
        puts "ollama pull #{model_tag}"
      else
        puts "#{model_tag.yellow} needs to be updated (#{from_tags[model_tag][:size]})"
      end
      c += 1
    end
  else
    puts "#{model_tag.red} not in the tags file" unless bash_output
    c += 1
  end
end

if c == 0
  puts 'Everything is up to date'.green unless bash_output
end
