#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'
require 'uri'
require 'csv'

LIBRARIES = %w[library]

def list_of_models
  data = []

  LIBRARIES.each do |library|
    puts "==> Checking #{library}"

    html = URI.open("https://ollama.ai/#{library}").read
    doc = Nokogiri::HTML(html)

    doc.search('//div[@id="repo"]/ul/li').each do |li|
      name = li.search('h2').first.content.strip
      desc = li.search('p').first.content.strip
      data << [library, name, desc]
    end
  end

  data.sort
end

def list_of_tags(library, model, debug)
  puts "==> Tags for #{library}/#{model}"

  html = URI.open("https://ollama.ai/#{library}/#{model}/tags").read

  doc = Nokogiri::HTML(html)

  tags = {}

  doc.search('//span[@class="font-mono"]').each do |span|
    a = span.parent.parent.parent
    tag = a['href'].split('/').last

    next if tag.include?('-q')
    next if tag.include?('-fp')
    next if tag.include?('-bf')

    hash, size, _ = span.parent.content.gsub(/\s+/, ' ').strip.split(' • ', 3)

    tags[tag] = {size: size, hash: hash}
  end

  tags
end

debug = ARGV.include?('-d')

data = {}
list_of_models.each do |(library, model, desc)|
  data[model] = {'desc' => desc, 'tags' => list_of_tags(library, model, debug)}
end

m = File.open('models.csv', 'w')
m.puts %w[model description].to_csv

t = File.open('tags.csv', 'w')
t.puts %w[model tag hash size].to_csv

data.each do |model, x|
  m.puts [model, x['desc']].to_csv

  x['tags'].each do |b, s|
    t.puts [model, b, s[:hash], s[:size]].join(',')
  end
end

m.close
t.close
