#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'
require 'uri'
require 'csv'

LIBRARIES = %w[library x]

def list_of_models
  data = []

  LIBRARIES.each do |library|
    puts "==> Checking #{library}"

    html = URI.open("https://ollama.ai/#{library}").read
    doc = Nokogiri::HTML(html)

    doc.search('//div[@id="repo"]/ul/li').each do |li|
      name = li.search('h2').first.content.strip
      desc = li.search('p').first.content.strip
      data << [library, name, desc]
    end
  end

  data.sort
end

def list_of_tags(library, model)
  puts "==> Tags for #{library}/#{model}"

  url = "https://ollama.ai/#{library}/#{model}/tags"
  html = URI.open(url).read

  doc = Nokogiri::HTML(html)

  tags = {}

  doc.search('//span[@class="font-mono"]').each do |span|
    a = span.parent.parent.parent
    name = a['href'].split('/').last
    name = "#{library}/#{name}" if library != 'library'
    tag = name.split(':').last

    next if tag.include?('-q')
    next if tag.include?('-a')
    next if tag.include?('-fp')
    next if tag.include?('-bf')
    next if tag.include?('cloud')

    hash, size, _ = span.parent.content.gsub(/\s+/, ' ').strip.split(' • ', 3)

    tags[name] = {size: size, hash: hash}
  end

  tags
end

data = {}
list_of_models.each do |(library, model, desc)|
  full_model = library == 'library' ? model : "#{library}/#{model}"

  data[full_model] = {'desc' => desc, 'tags' => list_of_tags(library, model)}
end

m = File.open('models.csv', 'w')
m.puts %w[model description].to_csv

t = File.open('tags.csv', 'w')
t.puts %w[model tag hash size].to_csv

data.each do |model, x|
  m.puts [model, x['desc']].to_csv

  x['tags'].each do |b, s|
    t.puts [model, b, s[:hash], s[:size]].join(',')
  end
end

m.close
t.close
